const actions = {
  GET_HOME_START: 'GET_HOME_START',
  GET_HOME_SUCCESS: 'GET_HOME_SUCCESS',
  GET_HOME_FAILED: 'GET_HOME_FAILED',
  GET_DASHBOARD: 'GET_DASHBOARD',

  POST_REGISTER_START: 'POST_REGISTER_START',
  POST_REGISTER_SUCCESS: 'POST_REGISTER_SUCCESS',
  POST_REGISTER_FAILED: 'POST_REGISTER_FAILED',
  RESET_REGISTER: 'RESET_REGISTER',

  POST_LOGIN_START: 'POST_LOGIN_START',
  POST_LOGIN_SUCCESS: 'POST_LOGIN_SUCCESS',
  POST_LOGIN_FAILED: 'POST_LOGIN_FAILED',

  AUTH_LOGOUT_START: 'AUTH_LOGOUT_START',
  AUTH_LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS',
  AUTH_LOGOUT_FAILED: 'AUTH_LOGOUT_FAILED',

  SET_PROFILE_START: 'SET_PROFILE_START',
  SET_PROFILE_SUCCESS: 'SET_PROFILE_SUCCESS',
  SET_PROFILE_FAILED: 'SET_PROFILE_FAILED',

  UPDATE_PROFILE_START: 'UPDATE_PROFILE_START',
  UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILED: 'UPDATE_PROFILE_FAILED',

  GET_CATEGORY_START: 'GET_CATEGORY_START',
  GET_CATEGORY_SUCCESS: 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_FAILED: 'GET_CATEGORY_FAILED',

  POST_CATEGORY_START: 'POST_CATEGORY_START',
  POST_CATEGORY_SUCCESS: 'POST_CATEGORY_SUCCESS',
  POST_CATEGORY_FAILED: 'POST_CATEGORY_FAILED',

  UPDATE_CATEGORY_START: 'UPDATE_CATEGORY_START',
  UPDATE_CATEGORY_SUCCESS: 'UPDATE_CATEGORY_SUCCESS',
  UPDATE_CATEGORY_FAILED: 'UPDATE_CATEGORY_FAILED',

  DELETE_CATEGORY_START: 'DELETE_CATEGORY_START',
  DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
  DELETE_CATEGORY_FAILED: 'DELETE_CATEGORY_FAILED',

  GET_PRODUCT_START: 'GET_PRODUCT_START',
  GET_PRODUCT_SUCCESS: 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILED: 'GET_PRODUCT_FAILED',

  POST_PRODUCT_START: 'POST_PRODUCT_START',
  POST_PRODUCT_SUCCESS: 'POST_PRODUCT_SUCCESS',
  POST_PRODUCT_FAILED: 'POST_PRODUCT_FAILED',

  UPDATE_PRODUCT_START: 'UPDATE_PRODUCT_START',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',

  DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',

  ADD_TO_CART_START: 'ADD_TO_CART_START',
  ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILED: 'ADD_TO_CART_FAILED',

  CHECK_OUT_START: 'CHECK_OUT_START',
  CHECK_OUT_SUCCESS: 'CHECK_OUT_SUCCESS',
  CHECK_OUT_FAILED: 'CHECK_OUT_FAILED',

  GET_TRANSACTION_START: 'GET_TRANSACTION_START',
  GET_TRANSACTION_SUCCESS: 'GET_TRANSACTION_SUCCESS',
  GET_TRANSACTION_FAILED: 'GET_TRANSACTION_FAILED',

  UPDATE_TRANSACTION_START: 'UPDATE_TRANSACTION_START',
  UPDATE_TRANSACTION_SUCCESS: 'UPDATE_TRANSACTION_SUCCESS',
  UPDATE_TRANSACTION_FAILED: 'UPDATE_TRANSACTION_FAILED'
};

export default actions;
