const actions = {
  GET_HOME_START: 'GET_HOME_START',
  GET_HOME_SUCCESS: 'GET_HOME_SUCCESS',
  GET_HOME_FAILED: 'GET_HOME_FAILED',

  POST_REGISTER_START: 'POST_REGISTER_START',
  POST_REGISTER_SUCCESS: 'POST_REGISTER_SUCCESS',
  POST_REGISTER_FAILED: 'POST_REGISTER_FAILED',
  RESET_REGISTER: 'RESET_REGISTER',

  POST_LOGIN_START: 'POST_LOGIN_START',
  POST_LOGIN_SUCCESS: 'POST_LOGIN_SUCCESS',
  POST_LOGIN_FAILED: 'POST_LOGIN_FAILED',

  AUTH_LOGOUT: 'AUTH_LOGOUT'
};

export default actions;
